name: 'Rover Terraform Plan Visualisation'
description: 'Web based visualisation for Terraform plan'
inputs:
  terraform-root-directory: 
    description: 'Root Terraform directory within repo'
    required: false
    default: 'terraform'
  terraform-backend-config:
    description: 'Relative path to terraform-root-directory for the Terraform backend configuration file. Can be empty file if not applicable'
    required: true
  terraform-vars-file:
    description: 'Relative path to terraform-root-directory for the Terraform input vars file. Can be empty file if not applicable'
    required: true
  gh-pages-branch:
    description: 'Branch name for Rover output for GitHub Pages site'
    required: false
    default: 'gh-pages'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.terraform-root-directory }}
    - ${{ inputs.terraform-backend-config }}
    - ${{ inputs.terraform-vars-file }}
    - ${{ inputs.gh-pages-branch }}

# every workflow run has this ${{ secrets.GITHUB_TOKEN }} https://docs.github.com/en/actions/security-guides/automatic-token-authentication
#     - name: Deploy 🚀
#       uses: JamesIves/github-pages-deploy-action@v4
#       with:
#         folder: rover-website
#         branch: ${{ inputs.gh-pages-branch }}
#         target-folder: rover
branding:
  icon: settings
  color: orange